apiVersion: cluster.x-k8s.io/v1alpha3
kind: Cluster
metadata:
  name: firekube
  namespace: weavek8sops
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    serviceDomain: cluster.local
    services:
      cidrBlocks:
      - 10.96.0.0/12
  infrastructureRef:
    apiVersion: cluster.weave.works/v1alpha3
    kind: ExistingInfraCluster
    name: firekube
---
apiVersion: cluster.weave.works/v1alpha3
kind: ExistingInfraCluster
metadata:
  name: firekube
  namespace: weavek8sops
spec:
  apiServer:
    extraArguments:
    - name: alsologtostderr
      value: "true"
  cri:
    kind: docker
    package: docker-ce
    version: 19.03.8
  kubeletArguments:
  - name: alsologtostderr
    value: "true"
  - name: container-runtime
    value: docker
  os:
    files:
    - destination: /etc/yum.repos.d/kubernetes.repo
      source:
        configmap: repo
        key: kubernetes.repo
    - destination: /etc/yum.repos.d/docker-ce.repo
      source:
        configmap: repo
        key: docker-ce.repo
    - destination: /etc/docker/daemon.json
      source:
        configmap: docker
        key: daemon.json
  user: root
