apiVersion: cluster.x-k8s.io/v1alpha3
kind: Machine
metadata:
  labels:
    set: master
  name: master-0
  namespace: weavek8sops
spec:
  bootstrap: {}
  clusterName: firekube
  infrastructureRef:
    apiVersion: cluster.weave.works/v1alpha3
    kind: ExistingInfraMachine
    name: master-0
  version: 1.17.11
---
apiVersion: cluster.weave.works/v1alpha3
kind: ExistingInfraMachine
metadata:
  name: master-0
  namespace: weavek8sops
spec:
  private:
    address: 172.25.0.2
    port: 22
  public:
    address: 127.0.0.1
    port: 2222
